name: Loan Application Approval

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.12

      - name: Install dependencies
        run: make -C src install

      - name: Lint with pylint
        run: make -C src lint

      - name: Test with pytest
        run: make -C src test

      - name: Format code
        run: make -C src format
